# dotfiles
# Kashev Dalmia | @kashev | kashev.dalmia@gmail.com
# config.yaml

# The configuration file for install.py.

# Paths to install settings folders to.
paths:
  git:
    path: "~"
    dot: true
  vim:
    path: "~"
    dot: true

  # ZSH and Shell Options
  zsh:
    path: "~"
    dot: true
  bash:
    path: "~"
    dot: true

  gnome-apps:
    path: "~/.gconf/apps"
    dot: false

  # ST3 Location as installed through this PPA:
  # http://www.webupd8.org/2013/07/sublime-text-3-ubuntu-ppa-now-available.html
  sublimetext:
    path: "~/.config/sublime-text-3/Packages/User"
    dot: false

options:
  shell: "zsh"
