# dotfiles
# Kashev Dalmia | @kashev | kashev.dalmia@gmail.com
# config.yaml
#
# The configuration file for install.py.

# Paths to install settings folders to.
paths:
  git: "~"
  vim: "~"
  zsh: "~"
  # ST3 Location as installed through this PPA:
  # http://www.webupd8.org/2013/07/sublime-text-3-ubuntu-ppa-now-available.html
  sublimetext: "~/.config/sublime-text-3/Packages/User"


# External dependencies to install
to_install:
  # Packages to install using the system package manager.
  linux:
    # Development, shell, etc.
    - "git"
    - "vim"
    - "zsh"
    # Python related packages
    - "python"
    - "python-pip"
    - "bpython" # https://github.com/bpython/bpython
    # Gnome Related Packages
    - "gnome-shell"
    - "gconf-editor"
    # Media and Web
    - "google-chrome"
    - "vlc"

  # Packages to install on Ubuntu only.
  ubuntu:
    - "ubuntu-gnome-desktop"

  # Packages to install using pip.
  pip:
    - "pep8"
    - "pyyaml"
