# dotfiles
# Kashev Dalmia | @kashev | kashev.dalmia@gmail.com
# config.yaml

# The configuration file for install.py.

# Paths to install settings folders to.
paths:
  git:
    path: "~"
    dot: true
  vim:
    path: "~"
    dot: true
  tmux:
    path: "~"
    dot: true

  # ZSH and Shell Options
  zsh:
    path: "~"
    dot: true
  bash:
    path: "~"
    dot: true

  terminator:
    path: "~/.config/terminator"
    dot: false

  # ST3 settings location as installed by the official PPA
  sublimetext:
    path: "~/.config/sublime-text-3/Packages/User"
    dot: false

  # Visual Studio Code settings location, as installed through the .deb.
  vscode:
    path: "~/.config/Code/User"
    dot: false

options:
  shell: "zsh"
