#!/usr/bin/env bash
# This hook is sourced after every virtualenv is activated.

# Source: http://virtualenvwrapper.readthedocs.org/en/latest/tips.html#zsh-prompt
PS1="$_OLD_VIRTUAL_PS1"
_OLD_RPROMPT="$RPROMPT"
RPROMPT="%{${fg_bold[white]}%}(env: %{${fg[green]}%}`basename \"$VIRTUAL_ENV\"`%{${fg_bold[white]}%})%{${reset_color}%} $RPROMPT"
