" dotfiles
" Kashev Dalmia | @kashev | kashev.dalmia@gmail.com
" vimrc

syntax on         " Turn on syntax highlighting.
set smartindent   " Turn on Smart Indenting.
set tabstop=4     " Tabs are 4 spaces.
set expandtab     " Tabs are spaces.
set shiftwidth=4  " When I indent, it's 4 spaces.
set number        " Show line numbers.

" Rulers
set ruler          " Show cursor position at the bottom of the screen.
set colorcolumn=81 " Show a highlighted column *after* 80 characters.
