#!/usr/bin/env zsh
# dotfiles
# Kashev Dalmia | @kashev | kashev.dalmia@gmail.com

#########
# zshrc #
#########

###########################
# oh-my-zsh Configuration #
###########################

# oh-my-zsh Installation Location
export ZSH=$HOME/.oh-my-zsh

# Custom oh-my-zsh-custom Folder
ZSH_CUSTOM=$HOME/.oh-my-zsh-custom

# Other oh-my-zsh Options
ZSH_THEME="kashev"
COMPLETION_WAITING_DOTS="true"

# oh-my-zsh Plugins
plugins=(
    colored-man
    command-not-found
    git
    sublime
    wd
    web-search
    zsh_reload
)

# Load oh-my-zsh #
source $ZSH/oh-my-zsh.sh

######################
# User Configuration #
######################

export PATH=$HOME/bin:/usr/local/bin:$PATH

# Change History to not share incremental history between terminals.
setopt append_history no_share_history

# Set a HOSTNAME variable, like in bash
export HOSTNAME=`hostname`

export BROWSER=google-chrome

#######################
# Add Scripts to Path #
#######################
export PATH=$PATH:$HOME/.shell-scripts

##############################
# Long Command Configuration #
##############################

# Report CPU usage for commands running longer than 10 seconds
# Thanks to http://nuclearsquid.com/writings/reporttime-in-zsh/
REPORTTIME=10

#############################
# VIRTUAL ENV CONFIGURATION #
#############################
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/dev
source /usr/local/bin/virtualenvwrapper.sh

###########################
# Base16 Colors Installer #
###########################
BASE16_SHELL="$HOME/.shell-scripts/base16-monokai.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL



