#!/usr/bin/env bash
# dotfiles
# Kashev Dalmia | @kashev | kashev.dalmia@gmail.com

# Git up to date.

set -e
set -x

BRANCH=${1:-master}

git checkout $BRANCH
git pull
git checkout -
git rebase $BRANCH
