#!/usr/bin/env zsh
# dotfiles
# Kashev Dalmia | @kashev | kashev.dalmia@gmail.com

# One stop shop for living on the bleeding Ubuntu edge.
set -e
sudo apt update
sudo apt upgrade --with-new-pkgs
sudo apt autoremove
