#!/usr/bin/env zsh
# dotfiles
# Kashev Dalmia | @kashev | kashev.dalmia@gmail.com

# One stop shop for living on the bleeding Ubuntu edge.
set -e
sudo apt-get update
sudo apt-get upgrade
sudo apt-get autoremove
